### PR TITLE
[CI] update CI to keep same with github action template

### PR DESCRIPTION
**Pull request by SamYuan1990**
1. update CI with ci.yml as before and after PR level check, make it same with our example in readme document to keep user's input been tested with our CI.
2. decouple a PR image build and publish process with before and after PR check.
3. fix lint issue
4. fix action input define issue
5. fix action output define issue.

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@rootfs , to keep the same usage for user and CI, we have to follow https://github.com/actions/hello-world-docker-action/blob/main/.github/workflows/ci.yml#L65-L69 to set up CI for this repo instead of just `docker run ...` hence I made this PR and try to fix some issues found today. could you please help check with https://github.com/sustainable-computing-io/aws_ec2_self_hosted_runner/actions/runs/7276597255/job/19826767572 I am confused a little for why the action is missing.

**Comment by SamYuan1990** [comment]
ok I got lint issue been fixed.

**Comment by SamYuan1990** [comment]
but https://github.com/sustainable-computing-io/aws_ec2_self_hosted_runner/actions/runs/7276748449/job/19827220326?pr=5 security group id is still missing.

**Comment by SamYuan1990** [comment]
@rootfs , could you please help check secret settings for https://github.com/sustainable-computing-io/aws_ec2_self_hosted_runner/actions/runs/7276748449/job/19827220326?pr=5#step:1:20

**Comment by SamYuan1990** [comment]
Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork. ....

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
@SamYuan1990 can you check the test errors? The docker action has its own env var naming convention, all the input parameters must start with `INPUT_` (see [here](https://github.com/sustainable-computing-io/aws_ec2_self_hosted_runner/blob/main/.github/workflows/pr.yml#L55)), and the script convert the `INPUT_` env var to its own internal names (see [here](https://github.com/sustainable-computing-io/aws_ec2_self_hosted_runner/blob/main/entrypoint.sh#L286))

**Comment by SamYuan1990** [comment]
> @SamYuan1990 can you check the test errors? The docker action has its own env var naming convention, all the input parameters must start with `INPUT_` (see [here](https://github.com/sustainable-computing-io/aws_ec2_self_hosted_runner/blob/main/.github/workflows/pr.yml#L55)), and the script convert the `INPUT_` env var to its own internal names (see [here](https://github.com/sustainable-computing-io/aws_ec2_self_hosted_runner/blob/main/entrypoint.sh#L286))

I suppose the difference is between https://github.com/sustainable-computing-io/aws_ec2_self_hosted_runner/actions/runs/7225181901/job/19688062061#step:1:20 and https://github.com/sustainable-computing-io/aws_ec2_self_hosted_runner/actions/runs/7276748449/job/19827220326?pr=5#step:1:20
as we can see the Secret source are different. let me try to verify via another PR.

**Comment by SamYuan1990** [comment]
close this as this will not works due to github action security setting, switch to #6

**Pull request closed without merging**
